nelmio_api_doc:
    documentation:
        info:
            title: Print4Health
            description: ~
            version: 1.0.0
    areas:
        path_patterns:
            - ^/(login|request-password-reset|reset-password|user)
