# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
